# This config has been generated by the pocket_coffea CLI 0.9.13.
from pocket_coffea.utils.configurator import Configurator
from pocket_coffea.lib.cut_definition import Cut
from pocket_coffea.lib.cut_functions import get_nObj_min, get_HLTsel
from pocket_coffea.lib.weights.common.common import genWeight, lumi, XS
from pocket_coffea.parameters.cuts import passthrough
from pocket_coffea.parameters.histograms import *

import workflow
from workflow import DelphesProcessor

# Register custom modules in cloudpickle to propagate them to dask workers
import cloudpickle
import custom_cut_functions
cloudpickle.register_pickle_by_value(workflow)
cloudpickle.register_pickle_by_value(custom_cut_functions)

from custom_cut_functions import *
import os
localdir = os.path.dirname(os.path.abspath(__file__))

# Loading default parameters
from pocket_coffea.parameters import defaults
default_parameters = defaults.get_default_parameters()
defaults.register_configuration_dir("config_dir", localdir+"/params")

parameters = defaults.merge_parameters_from_files(default_parameters,
                                                    f"{localdir}/params/object_preselection.yaml",
                                                    #f"{localdir}/params/triggers.yaml",
                                                    #f"{localdir}/params/plotting.yaml",
                                                   update=True)
cfg = Configurator(
    parameters = parameters,
    datasets = {
        "jsons": [f'{localdir}/dataset_definition.json'],
        "filter" : {
            "samples": ['ttphi_c1_1p0_c101_1p0_13p6TeV_mde25'],
            "samples_exclude" : [],
            "year": ['2024']
        }
    },

    workflow = DelphesProcessor,

    # Delphes: no object calibrations (the default sequence is NanoAOD/JEC-specific)
    # and only the generator weight, luminosity and cross section as weights
    calibrators = [],
    weights_classes = [genWeight, lumi, XS],

    skim = [

    ],

    preselections = [semileptonic_presel],
    categories = {
        "baseline": [passthrough],
        "4j3b": [get_nObj_min(4, coll="JetGood"), get_nObj_min(3, coll="BJetGood")],
        "4j4b": [get_nObj_min(4, coll="JetGood"), get_nObj_min(4, coll="BJetGood")],
        "5j3b": [get_nObj_min(5, coll="JetGood"), get_nObj_min(3, coll="BJetGood")],
        "5j4b": [get_nObj_min(5, coll="JetGood"), get_nObj_min(4, coll="BJetGood")],
        "6j3b": [get_nObj_min(6, coll="JetGood"), get_nObj_min(3, coll="BJetGood")],
        "6j4b": [get_nObj_min(6, coll="JetGood"), get_nObj_min(4, coll="BJetGood")],
    },

    weights = {
        "common": {
            "inclusive": ["genWeight","lumi","XS"],
            "bycategory": {
                          },
       },
        "bycategory" : {
                       },

        "bysample": {
        }
    },

    variations = {
        "weights": {
            "common": {
                "inclusive": [ ],
                "bycategory" : {
                }
            },
        "bysample": {
                    },
        "bycategory": {
                    }
        },
    },

    variables = {
        # Only fields available in Delphes objects (pt/eta/phi via the schema aliases,
        # pdgId from the workflow); no tagger scores, no MET.pt
        **count_hist("JetGood", bins=10, start=0, stop=10),
        **count_hist("BJetGood", bins=6, start=0, stop=6),
        **jet_hists(coll="JetGood", pos=0),
        **lepton_hists(coll="LeptonGood", pos=0),
        "MissingET": HistConf([Axis(coll="MissingET", field="MET", bins=40, start=0, stop=400, label="MET [GeV]")]),
    },

    columns = {

    },
)
