# This config has been generated by the pocket_coffea CLI 0.9.13.
from pocket_coffea.utils.configurator import Configurator
from pocket_coffea.lib.cut_definition import Cut
from pocket_coffea.lib.cut_functions import get_nObj_min, get_HLTsel
from pocket_coffea.parameters.cuts import passthrough
from pocket_coffea.parameters.histograms import *

import workflow
from workflow import DelphesProcessor

# Register custom modules in cloudpickle to propagate them to dask workers
import cloudpickle
import custom_cut_functions
cloudpickle.register_pickle_by_value(workflow)
cloudpickle.register_pickle_by_value(custom_cut_functions)

from custom_cut_functions import *
import os
localdir = os.path.dirname(os.path.abspath(__file__))

# Loading default parameters
from pocket_coffea.parameters import defaults
default_parameters = defaults.get_default_parameters()
defaults.register_configuration_dir("config_dir", localdir+"/params")

parameters = defaults.merge_parameters_from_files(default_parameters,
                                                    f"{localdir}/params/object_preselection.yaml",
                                                    #f"{localdir}/params/triggers.yaml",
                                                    #f"{localdir}/params/plotting.yaml",
                                                   update=True)
cfg = Configurator(
    parameters = parameters,
    datasets = {
        "jsons": [f'{localdir}/dataset_definition.json'],
        "filter" : {
            "samples": ['ttphi_c1_1p0_c101_1p0_13p6TeV_mde25'],
            "samples_exclude" : [],
            "year": ['2024']
        }
    },

    workflow = DelphesProcessor,

    skim = [

    ], 

    preselections = [semileptonic_presel],
    categories = {
        "baseline": [passthrough],
        "4j3b": [get_nObj_min("JetGood", 4), get_nObj_min("BJetGood", 3)],
        "4j4b": [get_nObj_min("JetGood", 4), get_nObj_min("BJetGood", 2)],
        "5j3b": [get_nObj_min("JetGood", 5), get_nObj_min("BJetGood", 3)],
        "5j4b": [get_nObj_min("JetGood", 5), get_nObj_min("BJetGood", 4)],
        "6j3b": [get_nObj_min("JetGood", 6), get_nObj_min("BJetGood", 3)],
        "6j4b": [get_nObj_min("JetGood", 6), get_nObj_min("BJetGood", 4)],
    },

    weights = {
        "common": {
            "inclusive": ["genWeight","lumi","XS",
                          "pileup"],
            "bycategory": {
                          },
       },
        "bycategory" : {
                       },
        
        "bysample": {
        }
    },

    variations = {
        "weights": {
            "common": {
                "inclusive": [ ],
                "bycategory" : {
                }
            },
        "bysample": {
                    },
        "bycategory": {
                    }
        },
    },

    variables = {


    },

    columns = {

    },
)
