# This code has been generated by the pocket_coffea CLI 0.9.13.
import awkward as ak
import numpy as np
from pocket_coffea.lib.cut_definition import Cut

def cut_function(events, params, year, sample, **kwargs):
    # Put here your selection logic
    return np.ones(len(events), dtype=bool)

def semileptonic(events, params, year, sample, **kwargs):

    has_one_electron = events.nElectronGood == 1
    has_one_muon = events.nMuonGood == 1

    mask = (
        (events.nLeptonGood == 1)
        &
        # Here we properly distinguish between leading muon and leading electron
        (
            (
                has_one_electron
                & (
                    ak.firsts(events.LeptonGood.pt)
                    > params["pt_leading_electron"][year]
                )
            )
            | (
                has_one_muon
                & (ak.firsts(events.LeptonGood.pt) > params["pt_leading_muon"][year])
            )
        )
        #& (events.nLeptonVeto == 0)
        & (events.nJetGood >= params["njet"])
        & (events.nBJetGood >= params["nbjet"])
        & (events.MissingET.MET > params["met"])  # Delphes MissingET is a per-event singleton
    )

    # Pad None values with False
    return ak.where(ak.is_none(mask), False, mask)

semileptonic_presel= Cut(
    name="semileptonic",
    params={
        "njet": 4,
        "nbjet": 2,
        "pt_leading_electron": {
            '2022_preEE': 30,
            '2022_postEE': 30,
            '2023_preBPix': 30,
            '2023_postBPix': 30,
            '2024': 30,
            '2025': 30,
        },
        "pt_leading_muon": {
            '2022_preEE': 26,
            '2022_postEE': 26,
            '2023_preBPix': 26,
            '2023_postBPix': 26,
            '2024': 26,
            '2025': 26,
        },
        "met": 20,
    },
    function=semileptonic,
)

